// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmib1elI5uXPmPxqK8XSaS_qap_bhjfkU',
    appId: '1:1079276447565:web:a69c75a3baf1f682f53904',
    messagingSenderId: '1079276447565',
    projectId: 'flutterpasswordmanager-a44f7',
    authDomain: 'flutterpasswordmanager-a44f7.firebaseapp.com',
    storageBucket: 'flutterpasswordmanager-a44f7.appspot.com',
    measurementId: 'G-KQ8P123MEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqeiqCjayUY_xqQz-m2KfCR6IgjiZVpY4',
    appId: '1:1079276447565:android:106756db9bfbcdadf53904',
    messagingSenderId: '1079276447565',
    projectId: 'flutterpasswordmanager-a44f7',
    storageBucket: 'flutterpasswordmanager-a44f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEclNh30fBFNGgFHAQHvZO7RzEwHz17xk',
    appId: '1:1079276447565:ios:22fc0f6ffff854eff53904',
    messagingSenderId: '1079276447565',
    projectId: 'flutterpasswordmanager-a44f7',
    storageBucket: 'flutterpasswordmanager-a44f7.appspot.com',
    iosClientId: '1079276447565-s4023lr0hv3tbg3tsdbcks4ndsj4u3nn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPasswordManager',
  );
}
